### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by joaquinito2070** [dtankdempse/free-iptv-channels#15]
Gives error in all playlists provided by i.mjh.nz:
Error fetching data and no cached data available: Error en la solicitud para el código devuelto 404 de https://i.mjh.nz. Respuesta del servidor truncada: <html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
 (usar la opción muteHttpExceptions para examinar toda la respuesta)
 Please fix it.

**Comment by Mikhel** [comment]
> Gives error in all playlists provided by i.mjh.nz: Error fetching data and no cached data available: Error en la solicitud para el código devuelto 404 de https://i.mjh.nz. Respuesta del servidor truncada:
> 
> <title>404 Not Found</title>
> # 404 Not Found
> nginx (usar la opción muteHttpExceptions para examinar toda la respuesta) Please fix it.

Matt is not hosting any playlists, it only has EPG files (xml and xml.gz).

**Comment by joaquinito2070** [comment]
.app.json not found Plex, etc.

**Comment by dtankdempse** [comment]
> .app.json not found Plex, etc.

Plex has been fixed on the hosted script. I likely won't get to the other scripts until later.

**Comment by ovargasp** [comment]
Plex stopped working for me some hours ago, the error says Error: Failed to fetch data. 

PlutoTv, Samsung and Stirr that are the other ones that I'm using are working fine... I'm using the docker version I don't know if that has something to do with it...

**Comment by dtankdempse** [comment]
> Plex stopped working for me some hours ago, the error says Error: Failed to fetch data.
> 
> PlutoTv, Samsung and Stirr that are the other ones that I'm using are working fine... I'm using the docker version I don't know if that has something to do with it...

I've now uploaded the latest updates for Plex to Docker Hub.

**Comment by ovargasp** [comment]
Thanks I just updated and everything it's working now... :clap:	:clap: :clap: :clap:

**Comment by pannetone** [comment]
I'm still getting the 404 error with my google script. Do I have to do something to fix it?

**Comment by Mikhel** [comment]
> I'm still getting the 404 error with my google script. Do I have to do something to fix it?

Yes, modify yours so it is identical to the one DTankDempse shared with us.

This one:
https://github.com/dtankdempse/free-iptv-channels/blob/main/code.gs

Saludos.
